heat_template_version: "2018-08-31"
resources:
  test_key:
    type: OS::Nova::KeyPair
    properties:
      save_private_key: true
      name: test_key

  instance_port:
    type: OS::Neutron::Port
    properties:
      network: testNetwork
      fixed_ips:
        - subnet_id: "testSubnet"

  testVM:
    type: OS::Nova::Server
    properties:
      flavor: default
      image: rhel8
      networks:
        - port: { get_resource: instance_port }
      key_name: { get_resource: test_key }

outputs:
  private_key:
    description: Private key
    value: { get_attr: [ test_key, private_key ] }
